session "LinLattice" = HOL +
  options [document = false]
  sessions
    "HOL-Library"
  directories
    "HWQ-U"
    "HWQ-TSQ"
  theories
    Model
    PureLib
    DistLib
    Termination
    StateLib
    DeqLib
    EnqLib
    L0Lemmas
    E1Lemmas
    E2Lemmas
    E3Lemmas
    D3Lemmas
    D4Lemmas
    L0Proof
    E1Proof
    E2Proof
    E3Proof
    D1Proof
    D2Proof
    D3Proof
    D4Proof
    SysInvProof
    ULinProof
    TSQModel
    SimLemmas
    SimProof
    TraceInv
    TraceProof
    NotSimLemmas
    NotSimProof