theory TSQModel
  imports Main 
    "../HWQ-U/Model"
begin

(* ========================================================== *)
(* 1. Basic TSQ types and the timestamp order                *)
(* ========================================================== *)

(* Timestamps are positive naturals, plus the distinguished maximal value TOP. *)
datatype ts_type = TS nat | TOP

(* Timestamp order <_ts *)
fun ts_less :: "ts_type \<Rightarrow> ts_type \<Rightarrow> bool" (infix "<\<^sub>t\<^sub>s" 50) where
  "ts_less (TS a) (TS b) = (a < b)" |
  "ts_less (TS a) TOP = True" |
  "ts_less TOP (TS b) = False" |
  "ts_less TOP TOP = False"

(* Node type: (nid, value, timestamp) *)
type_synonym ts_node = "nat \<times> nat \<times> ts_type"


(* ========================================================== *)
(* 2. SP-pool atomic operations                               *)
(* ========================================================== *)

(* This plays the role of insertion. The unique nid is generated by nid_counter in the system state, so we omit a separate pure insert function and append nodes directly in the transition rules via list @ [(nid, v, TOP)]. *)

(* getOldest(pid): return (nid, ts). If no eligible non-TOP node exists, return (BOT, TOP). *)
definition pool_getOldest :: "ts_node list \<Rightarrow> (nat \<times> ts_type)" where
  "pool_getOldest pool = (
     case pool of
       ((nid, v, ts) # _) \<Rightarrow> if ts \<noteq> TOP then (nid, ts) else (BOT, TOP)
     | [] \<Rightarrow> (BOT, TOP)
   )"

(* remove(pid, nid): try to remove the designated non-TOP node. Return (value, new_pool); on failure, return (BOT, original_pool). *)
fun pool_remove :: "ts_node list \<Rightarrow> nat \<Rightarrow> (nat \<times> ts_node list)" where
  "pool_remove [] _ = (BOT, [])" |
  "pool_remove ((nid, v, ts) # rest) target_nid = 
     (if nid = target_nid \<and> ts \<noteq> TOP then 
        (v, rest) 
      else 
        let (ret_v, new_rest) = pool_remove rest target_nid in
        (ret_v, (nid, v, ts) # new_rest))"

(* Modified setTimestamp: recursively update all matching entries.
   In the TSQ model, nid is unique, so this is physically equivalent to updating only the first match.
   The recursive formulation makes the set-based lemmas unconditional and substantially simplifies the proofs. *)
fun pool_setTs :: "ts_node list \<Rightarrow> nat \<Rightarrow> ts_type \<Rightarrow> ts_node list" where
  "pool_setTs [] _ _ = []" |
  "pool_setTs ((nid, v, old_ts) # rest) target_nid new_ts = 
     (if nid = target_nid \<and> old_ts = TOP then 
        (nid, v, new_ts) # pool_setTs rest target_nid new_ts
      else 
        (nid, v, old_ts) # pool_setTs rest target_nid new_ts)"


(* ========================================================== *)
(* 3. Global and local TSQ state                               *)
(* ========================================================== *)

record TState =
  t_pc :: "nat \<Rightarrow> string"
  pools :: "nat \<Rightarrow> ts_node list"
  ts_counter :: nat       (* Global timestamp allocator, initially 1 *)
  nid_counter :: nat      (* Global node-id allocator, initially 1 *)
  t_V_var :: nat          (* Value allocator used for data independence, initially 1 *)
  
  (* Local state for enq() *)
  t_v :: "nat \<Rightarrow> nat"
  t_nid :: "nat \<Rightarrow> nat"
  t_ts :: "nat \<Rightarrow> ts_type"
  
  (* Local state for deq() *)
  t_startTs :: "nat \<Rightarrow> ts_type"
  t_candNid :: "nat \<Rightarrow> nat"
  t_candTs :: "nat \<Rightarrow> ts_type"
  t_candPid :: "nat \<Rightarrow> nat"
  t_retV :: "nat \<Rightarrow> nat"
  t_scanned :: "nat \<Rightarrow> nat set" (* Processes already scanned in the current deq loop *)


(* ========================================================== *)
(* 4. Simulation relation R (HWQ -> TSQ)                       *)
(* Closely following Conditions 2-8 of Appendix D.2 in the proof manuscript *)
(* ========================================================== *)
(*
(* ========================================================================= *)
(* Coupled three-layer view: concrete state CState, abstract history state UState, and ghost TSQ state TState *)
(* ========================================================================= *)
definition Simulation_R :: "SysState \<Rightarrow> TState \<Rightarrow> bool" where
  "Simulation_R s ts \<equiv> (
    let cs = fst s; us = snd s in
    
    (* [Condition 2: program-counter alignment] *)
    (\<forall>p. c_program_counter cs p = ''L0'' \<longrightarrow> t_pc ts p = ''TL0'') \<and>
    (\<forall>p. c_program_counter cs p = ''E1'' \<longrightarrow> t_pc ts p = ''TE1'') \<and>
    (\<forall>p. c_program_counter cs p = ''E2'' \<longrightarrow> t_pc ts p = ''TE2'') \<and>
    (\<forall>p. c_program_counter cs p = ''E3'' \<longrightarrow> t_pc ts p = ''TE3'') \<and>
    (\<forall>p. c_program_counter cs p = ''D1'' \<longrightarrow> t_pc ts p = ''TD1'') \<and>
    (\<forall>p. c_program_counter cs p = ''D2'' \<longrightarrow> t_pc ts p = ''TD_Line4_Done'') \<and>
    (\<forall>p. c_program_counter cs p = ''D3'' \<longrightarrow> t_pc ts p = ''TD_Loop'') \<and>
    (\<forall>p. c_program_counter cs p = ''D4'' \<longrightarrow> t_pc ts p = ''TD_Remove_Done'') \<and>
    
    (* [Condition 3: well-formed timestamps of TSQ-pool nodes] *)
    (\<forall>p. \<forall>node\<in>set (pools ts p). snd (snd node) \<noteq> TOP \<or> snd (snd node) = TOP \<and> t_pc ts p = ''TE2'' \<and> t_nid ts p = fst node) \<and>
    
    (* [Condition 5.1: mapping for materialized queue entries] *)
    (\<forall>idx. CState.Q_arr cs idx \<noteq> BOT \<longrightarrow> (\<exists>u nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP)) \<and>
    
    (* [Condition 5.2: mapping for pending enqueue elements] *)
    (\<forall>u idx. CState.Q_arr cs idx = BOT \<and> c_program_counter cs u = ''E2'' \<and> CState.i_var cs u = idx \<longrightarrow> (\<exists>nid. (nid, CState.v_var cs u, TOP) \<in> set (pools ts u))) \<and>
    
    (* [Condition 6: one-way exact correspondence for the deq scan range] *)
    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>v. 
        (\<exists>idx<CState.j_var cs q. 
          (CState.Q_arr cs idx \<noteq> BOT \<and> (\<exists>nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts v) \<and> ts_val \<noteq> TOP)) \<or> 
          (CState.Q_arr cs idx = BOT \<and> c_program_counter cs v = ''E2'' \<and> CState.i_var cs v = idx \<and> idx \<noteq> BOT)) 
        \<longrightarrow> v \<in> t_scanned ts q)) \<and>
                 
    (* [Condition 7: uniqueness of the TOP (pending) node in an E2 process pool] *)
    (\<forall>q. c_program_counter cs q = ''E2'' \<longrightarrow> 
         length (filter (\<lambda>node. snd (snd node) = TOP) (pools ts q)) = 1) \<and>
           
    (* [Condition 8: startTs bounds every earlier visible timestamp along D2 and D3] *)
    (\<forall>p. c_program_counter cs p = ''D2'' \<or> c_program_counter cs p = ''D3'' \<longrightarrow>
         (\<forall>idx<CState.l_var cs p.
             (CState.Q_arr cs idx \<noteq> BOT \<longrightarrow>
              (\<forall>u nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts u) \<longrightarrow> ts_val <\<^sub>t\<^sub>s t_startTs ts p)) \<and>
             (\<forall>q. CState.Q_arr cs idx = BOT \<and> c_program_counter cs q = ''E2'' \<and> CState.i_var cs q = idx \<longrightarrow>
                  t_ts ts q <\<^sub>t\<^sub>s t_startTs ts p))) \<and>
                 
    (* [Condition 9: initial candidate values in the D3 loop] *)
    (\<forall>p. c_program_counter cs p = ''D3'' \<longrightarrow> 
        t_candNid ts p = BOT \<and> t_candTs ts p = TOP) \<and>
    
    (* [Condition 10: spatial correspondence via nid-index matching] *)
    (\<forall>u nid v n. (nid, v, TS n) \<in> set (pools ts u) \<longrightarrow> CState.Q_arr cs nid = v \<and> nid < CState.X_var cs) \<and>
    
    (* [Condition 11: value-range safety of ghost pools] *)
    (\<forall>u nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<longrightarrow> v \<in> Val) \<and>
    
    (* [Condition 12: synchronization of nid allocation and local slot indices] *)
    (nid_counter ts = CState.X_var cs) \<and>
    (\<forall>p. c_program_counter cs p \<in> {''E2'', ''E3''} \<longrightarrow> t_nid ts p = CState.i_var cs p) \<and>

    (* [Condition 13: timestamp-to-index monotonicity for materialized nodes] *)
    (\<forall>q. c_program_counter cs q \<in> {''D2'', ''D3'', ''D4''} \<longrightarrow>
         (\<forall>u nid v ts_val.
             (nid, v, ts_val) \<in> set (pools ts u) \<and>
             ts_val \<noteq> TOP \<and>
             \<not> ts_less (t_startTs ts q) ts_val \<longrightarrow>
             nid < CState.l_var cs q)) \<and> 

    (* [Condition 14: enqueue/dequeue coherence between timestamps and concrete indices] *)
    (\<forall>p q. c_program_counter cs p \<in> {''E2'', ''E3''} \<and> c_program_counter cs q \<in> {''D2'', ''D3'', ''D4''} \<and> \<not> ts_less (t_startTs ts q) (t_ts ts p) \<longrightarrow> CState.i_var cs p < CState.l_var cs q) \<and>

    (* [Condition 15: monotonicity of enqueue indices within pool histories] *)
    (\<forall>u. c_program_counter cs u = ''E2'' \<longrightarrow> 
         (\<forall>nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow> nid < CState.i_var cs u)) \<and>
    (\<forall>u. c_program_counter cs u = ''E3'' \<longrightarrow> 
         (\<forall>nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow> nid \<le> CState.i_var cs u)) \<and>

    (* [Condition 16: ownership bridge between ghost pools and abstract enqueue callers] *)
    (* Updated for the SSN-based Model.thy: quantify over the witness sn explicitly. *)
    (\<forall>u nid v ts_val. 
       (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow>
       (\<exists>sn. EnqCallInHis s u v sn)) \<and>

    (* [Condition 17: history completeness of the scanned set] *)
    (* Updated for the SSN-based Model.thy: quantify over the witness sn explicitly. *)
    (\<forall>q. c_program_counter (fst (cs, us)) q = ''D3'' \<longrightarrow> 
      (\<forall>v. v \<in> t_scanned ts q \<longrightarrow> 
        (\<exists>idx < CState.j_var (fst (cs, us)) q. 
          (c_program_counter (fst (cs, us)) v = ''E2'' \<and> CState.i_var (fst (cs, us)) v = idx) \<or> 
          (\<exists>v_val sn. EnqCallInHis (cs, us) v v_val sn \<and> 
                   InQBack (fst (cs, us), snd (cs, us)) v_val \<and> 
                   Idx (fst (cs, us), snd (cs, us)) v_val = idx)))) \<and>

    (* [Condition 18: time-space boundary for nodes already scanned during D3] *)
    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>v \<in> t_scanned ts q. \<forall>nid v_val ts_val. 
        (nid, v_val, ts_val) \<in> set (pools ts v) \<and> ts_val \<noteq> TOP \<longrightarrow> 
        nid < CState.j_var cs q \<or> \<not> ts_less ts_val (t_startTs ts q))) \<and>

    (* [Condition 19: boundary condition for pending enqueue nodes during D3 scans] *)
    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>u \<in> t_scanned ts q. c_program_counter cs u \<in> {''E2'', ''E3''} \<longrightarrow> 
        CState.i_var cs u < CState.j_var cs q \<or> \<not> ts_less (t_ts ts u) (t_startTs ts q))) \<and>

    (* [Condition 20: synchronization between the global value allocator and local snapshots] *)
    (CState.V_var cs = t_V_var ts \<and> (\<forall>p. c_program_counter cs p = ''E1'' \<longrightarrow> CState.v_var cs p = t_v ts p))
  )"
*)


definition Simulation_R :: "SysState \<Rightarrow> TState \<Rightarrow> bool" where
  "Simulation_R s ts \<equiv> (
    let cs = fst s; us = snd s in

    (\<forall>p. c_program_counter cs p = ''L0'' \<longrightarrow> t_pc ts p = ''TL0'') \<and>
    (\<forall>p. c_program_counter cs p = ''E1'' \<longrightarrow> t_pc ts p = ''TE1'') \<and>
    (\<forall>p. c_program_counter cs p = ''E2'' \<longrightarrow> t_pc ts p = ''TE2'') \<and>
    (\<forall>p. c_program_counter cs p = ''E3'' \<longrightarrow> t_pc ts p = ''TE3'') \<and>
    (\<forall>p. c_program_counter cs p = ''D1'' \<longrightarrow> t_pc ts p = ''TD1'') \<and>
    (\<forall>p. c_program_counter cs p = ''D2'' \<longrightarrow> t_pc ts p = ''TD_Line4_Done'') \<and>
    (\<forall>p. c_program_counter cs p = ''D3'' \<longrightarrow> t_pc ts p = ''TD_Loop'') \<and>
    (\<forall>p. c_program_counter cs p = ''D4'' \<longrightarrow> t_pc ts p = ''TD_Remove_Done'') \<and>

    (\<forall>p. \<forall>node\<in>set (pools ts p). snd (snd node) \<noteq> TOP \<or> snd (snd node) = TOP \<and> t_pc ts p = ''TE2'' \<and> t_nid ts p = fst node) \<and>

   (\<forall>idx. CState.Q_arr cs idx \<noteq> BOT \<longrightarrow> (\<exists>u\<in>ProcSet. \<exists>nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP)) \<and>

    (\<forall>u idx. CState.Q_arr cs idx = BOT \<and> c_program_counter cs u = ''E2'' \<and> CState.i_var cs u = idx \<longrightarrow> (\<exists>nid. (nid, CState.v_var cs u, TOP) \<in> set (pools ts u))) \<and>

    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>v. 
        (\<exists>idx<CState.j_var cs q. 
          (CState.Q_arr cs idx \<noteq> BOT \<and> (\<exists>nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts v) \<and> ts_val \<noteq> TOP)) \<or> 
          (CState.Q_arr cs idx = BOT \<and> c_program_counter cs v = ''E2'' \<and> CState.i_var cs v = idx \<and> idx \<noteq> BOT)) 
        \<longrightarrow> v \<in> t_scanned ts q)) \<and>

    (\<forall>q. c_program_counter cs q = ''E2'' \<longrightarrow> 
         length (filter (\<lambda>node. snd (snd node) = TOP) (pools ts q)) = 1) \<and>

    (\<forall>p. c_program_counter cs p = ''D2'' \<or> c_program_counter cs p = ''D3'' \<longrightarrow>
         (\<forall>idx<CState.l_var cs p.
             (CState.Q_arr cs idx \<noteq> BOT \<longrightarrow>
              (\<forall>u nid ts_val. (nid, CState.Q_arr cs idx, ts_val) \<in> set (pools ts u) \<longrightarrow> ts_val <\<^sub>t\<^sub>s t_startTs ts p)) \<and>
             (\<forall>q. CState.Q_arr cs idx = BOT \<and> c_program_counter cs q = ''E2'' \<and> CState.i_var cs q = idx \<longrightarrow>
                  t_ts ts q <\<^sub>t\<^sub>s t_startTs ts p))) \<and>

    (\<forall>p. c_program_counter cs p = ''D3'' \<longrightarrow> 
        t_candNid ts p = BOT \<and> t_candTs ts p = TOP) \<and>

    (\<forall>u nid v n. (nid, v, TS n) \<in> set (pools ts u) \<longrightarrow> CState.Q_arr cs nid = v \<and> nid < CState.X_var cs) \<and>

    (\<forall>u nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<longrightarrow> v \<in> Val) \<and>

    (nid_counter ts = CState.X_var cs) \<and>
    (\<forall>p. c_program_counter cs p \<in> {''E2'', ''E3''} \<longrightarrow> t_nid ts p = CState.i_var cs p) \<and>

    (\<forall>q. c_program_counter cs q \<in> {''D2'', ''D3'', ''D4''} \<longrightarrow> 
         (\<forall>u nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<and> \<not> ts_less (t_startTs ts q) ts_val \<longrightarrow> nid < CState.l_var cs q)) \<and>

    (\<forall>p q. c_program_counter cs p \<in> {''E2'', ''E3''} \<and> c_program_counter cs q \<in> {''D2'', ''D3'', ''D4''} \<and> \<not> ts_less (t_startTs ts q) (t_ts ts p) \<longrightarrow> CState.i_var cs p < CState.l_var cs q) \<and>

    (\<forall>u. c_program_counter cs u = ''E2'' \<longrightarrow> 
         (\<forall>nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow> nid < CState.i_var cs u)) \<and>
    (\<forall>u. c_program_counter cs u = ''E3'' \<longrightarrow> 
         (\<forall>nid v ts_val. (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow> nid \<le> CState.i_var cs u)) \<and>

    (\<forall>u nid v ts_val. 
       (nid, v, ts_val) \<in> set (pools ts u) \<and> ts_val \<noteq> TOP \<longrightarrow>
       (\<exists>sn. EnqCallInHis s u v sn)) \<and>

    (\<forall>q. c_program_counter (fst (cs, us)) q = ''D3'' \<longrightarrow> 
      (\<forall>v. v \<in> t_scanned ts q \<longrightarrow> 
        (\<exists>idx < CState.j_var (fst (cs, us)) q. 
          (c_program_counter (fst (cs, us)) v = ''E2'' \<and> CState.i_var (fst (cs, us)) v = idx) \<or> 
          (\<exists>v_val sn. EnqCallInHis (cs, us) v v_val sn \<and> 
                   InQBack (fst (cs, us), snd (cs, us)) v_val \<and> 
                   Idx (fst (cs, us), snd (cs, us)) v_val = idx)))) \<and>

    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>v \<in> t_scanned ts q. \<forall>nid v_val ts_val. 
        (nid, v_val, ts_val) \<in> set (pools ts v) \<and> ts_val \<noteq> TOP \<longrightarrow> 
        nid < CState.j_var cs q \<or> \<not> ts_less ts_val (t_startTs ts q))) \<and>

    (\<forall>q. c_program_counter cs q = ''D3'' \<longrightarrow> 
      (\<forall>u \<in> t_scanned ts q. c_program_counter cs u \<in> {''E2'', ''E3''} \<longrightarrow> 
        CState.i_var cs u < CState.j_var cs q \<or> \<not> ts_less (t_ts ts u) (t_startTs ts q))) \<and>

    (CState.V_var cs = t_V_var ts \<and> (\<forall>p. c_program_counter cs p = ''E1'' \<longrightarrow> CState.v_var cs p = t_v ts p))

  )"




(* ========================================================== *)
(* TSQ state invariant (TSQ_State_Inv)                        *)
(* 1. Data independence and node uniqueness in the pools      *)
(*    - distinct nodes cannot share the same value;           *)
(*    - equal nid implies the same owner process and timestamp. *)
(*                                                            *)
(* 2. Timestamp well-formedness of pool nodes                 *)
(*    - every non-TOP timestamp is below ts_counter.          *)
(*                                                            *)
(* 3. Well-formedness of the local timestamp variable t_ts    *)
(*    - every non-TOP t_ts is below ts_counter.               *)
(*                                                            *)
(* 4. Processes in TD_Line4_Done / TD_Loop / TD_Remove_Done  *)
(*    - their startTs is below ts_counter.                    *)
(*                                                            *)
(* 5. Local-state constraints in phase TE2                    *)
(*    - t_ts is non-TOP, and the pool contains the matching TOP node. *)
(*                                                            *)
(* 6. Local-state constraints in phase TE3                    *)
(*    - t_ts is non-TOP.                                       *)
(*                                                            *)
(* 7. Well-formedness of scanned sets                         *)
(*    - each scanned set is a subset of ProcSet.              *)
(*                                                            *)
(* 8. Timestamp order agrees with nid order for non-TOP nodes *)
(*    - ts1 < ts2 iff nid1 < nid2.                             *)
(*                                                            *)
(* 9. t_V_var always stays above BOT                           *)
(*                                                            *)
(* 10. Every pool value is below t_V_var                       *)
(*                                                            *)
(* 11. Every nid in the pools is below nid_counter             *)
(*                                                            *)
(* 12. Source discipline for TOP nodes                         *)
(*    - if ts_val = TOP, then the owner process is in TE2 and nid = t_nid. *)
(*                                                            *)
(* 13. Uniqueness of non-TOP timestamps                        *)
(*    - ts1 = ts2 implies nid1 = nid2.                         *)
(*                                                            *)
(* 14. A TE2-local timestamp does not clash with pool timestamps *)
(*                                                            *)
(* 15. Local timestamps of different TE2 processes are distinct *)
(*                                                            *)
(* 16. Structural well-formedness of each pool                 *)
(*    - each pool list is sorted and has distinct nid values.  *)
(*                                                            *)
(* 17. Validity and uniqueness of local values in phase TE1    *)
(*    - t_v is non-BOT and below t_V_var;                      *)
(*    - a TE1 value does not clash with any pool value;        *)
(*    - TE1 processes have pairwise distinct local values.     *)
(* ========================================================== *)

(* ========================================================== *)
(* Global TSQ-state invariant: data independence, timestamp validity, local-state constraints, and pool structure *)
(* ========================================================== *)
definition TSQ_State_Inv :: "TState \<Rightarrow> bool" where
  "TSQ_State_Inv ts \<equiv>
     (\<forall>p q nid1 nid2 v1 v2 ts1 ts2.
         (nid1, v1, ts1) \<in> set (pools ts p) \<and> (nid2, v2, ts2) \<in> set (pools ts q) \<longrightarrow>
         (v1 = v2) = (nid1 = nid2) \<and> (nid1 = nid2 \<longrightarrow> p = q \<and> ts1 = ts2)) \<and>

     (\<forall>p nid v ts_val.
         (nid, v, ts_val) \<in> set (pools ts p) \<and> ts_val \<noteq> TOP \<longrightarrow>
         ts_val <\<^sub>t\<^sub>s TS (ts_counter ts)) \<and>

     (\<forall>p.
         t_ts ts p \<noteq> TOP \<longrightarrow>
         t_ts ts p <\<^sub>t\<^sub>s TS (ts_counter ts)) \<and>

     (\<forall>q.
         t_pc ts q \<in> {''TD_Line4_Done'', ''TD_Loop'', ''TD_Remove_Done''} \<longrightarrow>
         t_startTs ts q <\<^sub>t\<^sub>s TS (ts_counter ts)) \<and>

     (\<forall>p.
         t_pc ts p = ''TE2'' \<longrightarrow>
         t_ts ts p \<noteq> TOP \<and>
         (\<exists>v. (t_nid ts p, v, TOP) \<in> set (pools ts p))) \<and>

         (\<forall>p.
         t_pc ts p = ''TE3'' \<longrightarrow>
         t_ts ts p \<noteq> TOP) \<and>

     (\<forall>p.
         t_scanned ts p \<subseteq> ProcSet) \<and>
  
    (\<forall>p q nid1 nid2 v1 v2 ts1 ts2.
          (nid1, v1, ts1) \<in> set (pools ts p) \<and>
          (nid2, v2, ts2) \<in> set (pools ts q) \<and>
          ts1 \<noteq> TOP \<and> ts2 \<noteq> TOP \<longrightarrow>
          (ts1 <\<^sub>t\<^sub>s ts2) = (nid1 < nid2)) \<and>
     (BOT < t_V_var ts) \<and>

     (\<forall>p nid v ts_val.
         (nid, v, ts_val) \<in> set (pools ts p) \<longrightarrow>
         v < t_V_var ts) \<and>

     (\<forall>p nid v ts_val.
         (nid, v, ts_val) \<in> set (pools ts p) \<longrightarrow>
         nid < nid_counter ts) \<and>

     (\<forall>p nid v ts_val.
         (nid, v, ts_val) \<in> set (pools ts p) \<and> ts_val = TOP \<longrightarrow>
         t_pc ts p = ''TE2'' \<and> nid = t_nid ts p) \<and>

     (\<forall>p q nid1 nid2 v1 v2 ts1 ts2.
         (nid1, v1, ts1) \<in> set (pools ts p) \<and>
         (nid2, v2, ts2) \<in> set (pools ts q) \<and>
         ts1 \<noteq> TOP \<and> ts2 \<noteq> TOP \<and> ts1 = ts2 \<longrightarrow>
         nid1 = nid2) \<and>

     (\<forall>p q nid v ts_val.
         t_pc ts p = ''TE2'' \<and>
         (nid, v, ts_val) \<in> set (pools ts q) \<and>
         ts_val \<noteq> TOP \<longrightarrow>
         t_ts ts p \<noteq> ts_val) \<and>

     (\<forall>p q.
         t_pc ts p = ''TE2'' \<and>
         t_pc ts q = ''TE2'' \<and>
         p \<noteq> q \<longrightarrow>
         t_ts ts p \<noteq> t_ts ts q) \<and>

     (\<forall>p.
         sorted (map fst (pools ts p)) \<and>
         distinct (map fst (pools ts p))) \<and>

     (\<forall>p.
         t_pc ts p = ''TE1'' \<longrightarrow>
         t_v ts p \<noteq> BOT \<and> t_v ts p < t_V_var ts) \<and>

     (\<forall>p q nid v ts_val.
         t_pc ts p = ''TE1'' \<and>
         (nid, v, ts_val) \<in> set (pools ts q) \<longrightarrow>
         t_v ts p \<noteq> v) \<and>

     (\<forall>p q.
         t_pc ts p = ''TE1'' \<and>
         t_pc ts q = ''TE1'' \<and>
         p \<noteq> q \<longrightarrow>
         t_v ts p \<noteq> t_v ts q)"

(* ========================================================== *)
(* Global refinement invariant                                  *)
(* Bundles the concrete invariants, the TSQ invariants, and the cross-layer simulation relation. *)
(* ========================================================== *)

definition Simulation_Inv :: "SysState \<Rightarrow> TState \<Rightarrow> bool" where
  "Simulation_Inv s ts \<equiv>
     system_invariant s \<and>          
     TSQ_State_Inv ts \<and>          
     Simulation_R s ts"  

(* ========================================================== *)
(* 4'. Minimal auxiliary notion for the D3-prefix semantics    *)
(* Notes:                                                     *)
(* - We do not introduce extra HWQ->TSQ coupling relations here. *)
(* - The counterexample only needs an explicit summary of the   *)
(*   scanned prefix of a D3 loop and its current candidate.     *)
(* ========================================================== *)

definition Cand_Summarizes_Scanned :: "TState \<Rightarrow> nat \<Rightarrow> bool" where
  "Cand_Summarizes_Scanned ts q \<equiv> (
    let S = t_scanned ts q;
        startTs = t_startTs ts q;
        cNid = t_candNid ts q;
        cTs = t_candTs ts q;
        cPid = t_candPid ts q
    in
    if (\<forall>k \<in> S. let (nid, tstamp) = pool_getOldest (pools ts k) in
                nid = BOT \<or> ts_less startTs tstamp)
    then
      cNid = BOT \<and> cTs = TOP \<and> cPid = BOT
    else
      cPid \<in> S \<and>
      (let (nid, tstamp) = pool_getOldest (pools ts cPid) in
         nid = cNid \<and> tstamp = cTs \<and> nid \<noteq> BOT \<and> \<not> ts_less startTs tstamp) \<and>
      (\<forall>k \<in> S. let (nid, tstamp) = pool_getOldest (pools ts k) in
         nid \<noteq> BOT \<and> \<not> ts_less startTs tstamp \<longrightarrow> \<not> ts_less tstamp cTs)
  )"

(* ========================================================== *)
(* 5. TSQ transition rules                                      *)
(* Following the TSQ enq() and deq() pseudocode closely         *)
(* ========================================================== *)

(* ---------------------------------------------------------- *)
(* Enqueue-side transitions                                     *)
(* ---------------------------------------------------------- *)

(* Corresponds to calling enq(v): allocate a fresh enqueue value. *)
definition T_Call_Enq :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_Call_Enq p ts ts' = (
    t_pc ts p = ''TL0'' \<and>
    ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TE1'' else t_pc ts x),
              t_V_var := t_V_var ts + 1,
              t_v := (\<lambda>x. if x = p then t_V_var ts else t_v ts x) \<rparr>
  )"

(* Corresponds to enq() Lines 2-3: insert a TOP node and generate a fresh timestamp. *)
definition T_E1 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_E1 p ts ts' = (
    t_pc ts p = ''TE1'' \<and>
    (let new_nid = nid_counter ts;
         val = t_v ts p;
         new_ts = ts_counter ts
     in
     ts' = ts\<lparr> nid_counter := new_nid + 1,
               ts_counter := new_ts + 1,
               t_nid := (\<lambda>x. if x = p then new_nid else t_nid ts x),
               t_ts := (\<lambda>x. if x = p then TS new_ts else t_ts ts x),
               pools := (\<lambda>x. if x = p then pools ts x @ [(new_nid, val, TOP)] else pools ts x),
               t_pc := (\<lambda>x. if x = p then ''TE2'' else t_pc ts x) \<rparr>)
  )"

(* Corresponds to enq() Line 4: replace TOP with the real timestamp. *)
definition T_E2 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_E2 p ts ts' = (
    t_pc ts p = ''TE2'' \<and>
    ts' = ts\<lparr> pools := (\<lambda>x. if x = p then pool_setTs (pools ts p) (t_nid ts p) (t_ts ts p) else pools ts x),
              t_pc := (\<lambda>x. if x = p then ''TE3'' else t_pc ts x) \<rparr>
  )"

(* Corresponds to the return step of enq(). *)
definition T_E3 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_E3 p ts ts' = (
    t_pc ts p = ''TE3'' \<and>
    ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TL0'' else t_pc ts x),
              t_v := (\<lambda>x. if x = p then BOT else t_v ts x),
              t_nid := (\<lambda>x. if x = p then BOT else t_nid ts x),
              t_ts := (\<lambda>x. if x = p then TOP else t_ts ts x) \<rparr>
  )"

(* ---------------------------------------------------------- *)
(* Dequeue-side transitions                                     *)
(* ---------------------------------------------------------- *)

(* Corresponds to calling deq(). *)
definition T_Call_Deq :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_Call_Deq p ts ts' = (
    t_pc ts p = ''TL0'' \<and>
    ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TD1'' else t_pc ts x) \<rparr>
  )"

(* Corresponds to deq() Lines 4-7: generate startTs and initialize all search variables. *)
definition T_D1 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D1 p ts ts' = (
    t_pc ts p = ''TD1'' \<and>
    (let new_ts = ts_counter ts in
     ts' = ts\<lparr> ts_counter := new_ts + 1,
               t_startTs := (\<lambda>x. if x = p then TS new_ts else t_startTs ts x),
               t_candNid := (\<lambda>x. if x = p then BOT else t_candNid ts x),
               t_candTs := (\<lambda>x. if x = p then TOP else t_candTs ts x),
               t_candPid := (\<lambda>x. if x = p then BOT else t_candPid ts x),
               t_scanned := (\<lambda>x. if x = p then {} else t_scanned ts x),
               t_pc := (\<lambda>x. if x = p then ''TD_Line4_Done'' else t_pc ts x) \<rparr>)
  )"

(* Corresponds to D2 entering the loop: reset all residual ghost state from the previous or retried attempt. *)
definition T_D2_EnterLoop :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D2_EnterLoop p ts ts' = (
    t_pc ts p = ''TD_Line4_Done'' \<and>
    ts' = ts\<lparr> 
      t_pc := (\<lambda>x. if x = p then ''TD_Loop'' else t_pc ts x),
      t_scanned := (\<lambda>x. if x = p then {} else t_scanned ts x),            
      t_candNid := (\<lambda>x. if x = p then BOT else t_candNid ts x),      
      t_candPid := (\<lambda>x. if x = p then BOT else t_candPid ts x),   
      t_candTs  := (\<lambda>x. if x = p then TOP else t_candTs ts x)      
    \<rparr>
  )"

(* Corresponds to deq() discovering emptiness and returning to D1 for a fresh snapshot. *)
definition T_D2_BackToD1 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D2_BackToD1 p ts ts' = (
    t_pc ts p = ''TD_Line4_Done'' \<and>
    ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TD1'' else t_pc ts x) \<rparr>
  )"

(* T_D2 contains both branches of the D2 control flow. *)
definition T_D2 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D2 p ts ts' = (T_D2_EnterLoop p ts ts' \<or> T_D2_BackToD1 p ts ts')"

(* Corresponds to the single scan iteration of deq() Lines 8-15: pick an unscanned process k and inspect its oldest node. *)
definition T_D3_Scan :: "nat \<Rightarrow> nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D3_Scan p k ts ts' = (
    t_pc ts p = ''TD_Loop'' \<and>
    k \<notin> t_scanned ts p \<and> 
    k \<in> ProcSet \<and>
    (let (nid, tstamp) = pool_getOldest (pools ts k);
         startTs = t_startTs ts p;
         candTs = t_candTs ts p;
         update = (nid \<noteq> BOT \<and> ts_less tstamp candTs \<and> \<not> (ts_less startTs tstamp))
     in
     ts' = ts\<lparr> t_candNid := (\<lambda>x. if x = p then (if update then nid else t_candNid ts p) else t_candNid ts x),
               t_candTs := (\<lambda>x. if x = p then (if update then tstamp else t_candTs ts p) else t_candTs ts x),
               t_candPid := (\<lambda>x. if x = p then (if update then k else t_candPid ts p) else t_candPid ts x),
               t_scanned := (\<lambda>x. if x = p then t_scanned ts p \<union> {k} else t_scanned ts x) \<rparr>)
  )"

(* Corresponds to deq() Lines 16-18: after all processes are scanned, execute remove and choose the next control state. *)
definition T_D3_Eval :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D3_Eval p ts ts' = (
    t_pc ts p = ''TD_Loop'' \<and>
    t_scanned ts p = ProcSet \<and>  
    (let cNid = t_candNid ts p;
         cPid = t_candPid ts p
     in
     if cNid \<noteq> BOT then
         let (val, new_pool) = pool_remove (pools ts cPid) cNid in
         if val \<noteq> BOT then
             ts' = ts\<lparr> pools := (\<lambda>x. if x = cPid then new_pool else pools ts x),
                       t_retV := (\<lambda>x. if x = p then val else t_retV ts x),
                       t_pc := (\<lambda>x. if x = p then ''TD_Remove_Done'' else t_pc ts x) \<rparr>
         else
             ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TD1'' else t_pc ts x) \<rparr>
     else
         ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TD1'' else t_pc ts x) \<rparr>
    )
  )"

(* ==================================================================== *)
(* 1. Reflexive-transitive closure of T_D3_Scan                 *)
(* Motivation: when the concrete layer is ready to commit a hit, *)
(* the ghost TSQ layer may still be missing part of ProcSet. This closure allows it to complete the remaining scans before evaluation. *)
(* ==================================================================== *)
inductive T_D3_Scan_Star :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  refl: "T_D3_Scan_Star p ts ts"
| step: "T_D3_Scan p k ts ts_mid \<Longrightarrow> T_D3_Scan_Star p ts_mid ts' \<Longrightarrow> T_D3_Scan_Star p ts ts'"


(* ========================================================== *)
(* D3 dispatcher used in the main development                   *)
(* Notes:                                                     *)
(* 1. Explicitly require the current process to be in TD_Loop.  *)
(* 2. Allow exactly three cases: one real scan / stuttering / evaluate after completing the scans. *)
(* 3. Exclude the unsound branch that jumps to TD1 without the required premises. *)
(* ========================================================== *)
definition T_D3 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D3 p ts ts' = (
     t_pc ts p = ''TD_Loop'' \<and>
     (
       (\<exists>k. T_D3_Scan p k ts ts') \<or>
       (ts' = ts) \<or>
       (\<exists>ts_mid. T_D3_Scan_Star p ts ts_mid \<and>
                 t_scanned ts_mid p = ProcSet \<and>
                 T_D3_Eval p ts_mid ts')
     )
   )"

(* ========================================================== *)
(* Alternative one-step D3 dispatcher                           *)
(* Notes:                                                     *)
(* - No reflexive-transitive closure of T_D3_Scan is used here. *)
(* - The counterexample should expose the shared prefix e1 itself, rather than compressing several scans into one step. *)
(* - Hence we keep only: one real scan / stuttering / evaluation when ProcSet has been fully scanned. *)
(* ========================================================== *)
definition T_D3' :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D3' p ts ts' = (
     t_pc ts p = ''TD_Loop'' \<and>
     (
       (\<exists>k. T_D3_Scan p k ts ts') \<or>
       (ts' = ts) \<or>
       (t_scanned ts p = ProcSet \<and> T_D3_Eval p ts ts')
     )
   )"

lemma T_D3'_into_T_D3:
  "T_D3' p ts ts' \<Longrightarrow> T_D3 p ts ts'"
  using T_D3'_def T_D3_Scan_Star.refl T_D3_def by auto

(* Corresponds to deq() Line 19: return the result. *)
definition T_D4 :: "nat \<Rightarrow> TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_D4 p ts ts' = (
    t_pc ts p = ''TD_Remove_Done'' \<and>
    ts' = ts\<lparr> t_pc := (\<lambda>x. if x = p then ''TL0'' else t_pc ts x),
              t_startTs := (\<lambda>x. if x = p then TOP else t_startTs ts x),
              t_candNid := (\<lambda>x. if x = p then BOT else t_candNid ts x),
              t_candTs := (\<lambda>x. if x = p then TOP else t_candTs ts x),
              t_candPid := (\<lambda>x. if x = p then BOT else t_candPid ts x),
              t_scanned := (\<lambda>x. if x = p then {} else t_scanned ts x),
              t_retV := (\<lambda>x. if x = p then BOT else t_retV ts x) \<rparr>
  )"

(* ========================================================== *)
(* 6. Initial TSQ state                                         *)
(* As in the paper: initially, pools(i) is the empty sequence.   *)
(* ========================================================== *)

definition T_Init :: "TState \<Rightarrow> bool" where
  "T_Init ts = (
    (\<forall>p. t_pc ts p = ''TL0'') \<and>
    (\<forall>p. pools ts p = []) \<and>
    ts_counter ts = 1 \<and>      
    nid_counter ts = 1 \<and>   
    t_V_var ts = 1 \<and>       
    
    (\<forall>p. t_v ts p = BOT) \<and>
    (\<forall>p. t_nid ts p = BOT) \<and>
    (\<forall>p. t_ts ts p = TOP) \<and>
    
    (\<forall>p. t_startTs ts p = TOP) \<and>
    (\<forall>p. t_candNid ts p = BOT) \<and>
    (\<forall>p. t_candTs ts p = TOP) \<and>
    (\<forall>p. t_candPid ts p = BOT) \<and>
    (\<forall>p. t_retV ts p = BOT) \<and>
    (\<forall>p. t_scanned ts p = {})
  )"

(* ========================================================== *)
(* Global Next relation for the TSQ ghost machine               *)
(* ========================================================== *)
definition T_Next :: "TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_Next ts ts' = (\<exists>p\<in>ProcSet. 
    T_Call_Enq p ts ts' \<or> T_E1 p ts ts' \<or> T_E2 p ts ts' \<or> T_E3 p ts ts' \<or>
    T_Call_Deq p ts ts' \<or> T_D1 p ts ts' \<or> T_D2 p ts ts' \<or> T_D3 p ts ts' \<or> T_D4 p ts ts' \<or>
    ts' = ts  
  )"

(* ========================================================== *)
(* Variant of the TSQ ghost-machine Next relation used in the non-simulation proof *)
(* ========================================================== *)
definition T_Next' :: "TState \<Rightarrow> TState \<Rightarrow> bool" where
  "T_Next' ts ts' = (\<exists>p\<in>ProcSet. 
    T_Call_Enq p ts ts' \<or> T_E1 p ts ts' \<or> T_E2 p ts ts' \<or> T_E3 p ts ts' \<or>
    T_Call_Deq p ts ts' \<or> T_D1 p ts ts' \<or> T_D2 p ts ts' \<or> T_D3' p ts ts' \<or> T_D4 p ts ts' \<or>
    ts' = ts  
  )"

lemma T_Next'_into_T_Next:
  "T_Next' ts ts' \<Longrightarrow> T_Next ts ts'"
  using T_D3'_into_T_D3 T_Next'_def T_Next_def by auto

(* ========================================================== *)
(* Reachability definitions                                      *)
(* ========================================================== *)

(* Reachability of the ghost TSQ machine *)
inductive Reachable_T :: "TState \<Rightarrow> bool" where
  init: "T_Init ts \<Longrightarrow> Reachable_T ts"
| step: "Reachable_T ts \<Longrightarrow> T_Next ts ts' \<Longrightarrow> Reachable_T ts'"

inductive Reachable_T' :: "TState \<Rightarrow> bool" where
  init: "T_Init ts \<Longrightarrow> Reachable_T' ts"
| step: "Reachable_T' ts \<Longrightarrow> T_Next' ts ts' \<Longrightarrow> Reachable_T' ts'"

lemma Reachable_T'_into_Reachable_T:
  "Reachable_T' ts \<Longrightarrow> Reachable_T ts"
proof (induction rule: Reachable_T'.induct)
  (* Step 1: lift the initial-state case directly. *)
  case (init ts)
  then show ?case
    by (rule Reachable_T.init)
next
  (* Step 2: lift one T_Next' step through T_Next. *)
  case (step ts ts')
  then show ?case
    by (meson Reachable_T.step T_Next'_into_T_Next)
qed

end